### NAMA = Tsabita Rosyidah Putri
### NPM = 22083010012

## SOAL

1. Cari dari website (maksimal 3) apapun data kontak bengkel kendaraan bermotor 
   yang ada di daerah surabaya dan sekitarnya. 
   Data kontak terdiri dari 
   a. Nama 
   b. Alamat 
   c. No Telp
   
   *cantumkan sumber/websitenya

2. Buatlah statistika deskriptif dari data yang didapatkan

3. Pilih salah satu dari daftar yang sudah didapatkan dan dapatkan pendapat publik
   (komentar) mengenai bengkel tersebut beberapa website (maksimal 3)
   
   *cantumkan sumber/websitenya

4. Buatlah statistika deskripstif dari data yang didapatkan
    
    *Dikumpulkan dalam bentuk file ipnyb

## JAWAB

### Website
#### Website 1 = https://www.autofun.co.id/bengkel-motor/cari-surabaya-dan-dengan-review
#### Website 2 = https://jejakpiknik.com/bengkel-motor-surabaya/

## WEB 1

In [1]:
from bs4 import BeautifulSoup 
import requests 
import pandas as pd

In [2]:
url = "https://www.autofun.co.id/bengkel-motor/cari-surabaya-dan-dengan-review"
req = requests.get(url)
print(req)

<Response [200]>

In [3]:
soup = BeautifulSoup(req.text, "html.parser")  
print(soup.link)

<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>

In [4]:
nama = []
alamat = []
nomer = []
rating = []
review = []
komentar = []

for i in soup.find_all('a', class_ = 'station-item wa-g-unit'):
    nyaringalamat = i.find('p').text
    if 'Kota SBY' in nyaringalamat:
        
        
        nyaringnama = i.find('img').get('alt')
        nyaringrating = i.find('div', class_ = 'rate')

        
        if nyaringrating:
            nyaringrating2 = nyaringrating.text.split()
            nyaringrating3 = float(nyaringrating2[0].replace(',', '.'))
            nyaringreview = int(nyaringrating2[1].replace('(', '').replace(')', ''))
            
        else:
            nyaringrating3 = 0.0
            nyaringreview = 0

        url2 = requests.get('https://www.autofun.co.id' + i.get('href'))
        nyarilink = BeautifulSoup(url2.text, 'html.parser')
        
        nyaringnomor = nyarilink.find('div', class_ = 'phone info-item')
        if nyaringnomor:
            nyaringnomor = nyaringnomor.text 
        else:
            nyaringnomor = '-'
        
        
        for j in nyarilink.find_all('p', class_ = 'text wa-ellipsis-3'):
            nyaringkomentar = j.text 
            
        nama.append(nyaringnama)
        alamat.append(nyaringalamat)
        review.append(nyaringreview)
        rating.append(nyaringrating3)
        nomer.append(nyaringnomor)
        komentar.append(nyaringkomentar)

In [5]:
df1 = pd.DataFrame({'Nama': nama, 'Alamat' : alamat, 'Review' : review, 'Nomer' : nomer, 'Rating' : rating, 'Komentar' : komentar })
df1

,Nama,Alamat,Review,Nomer,Rating,Komentar
0,HONDA AHASS 00663 BENTENG MOTOR SURABAYA,"Jl. Benteng No.18, Ujung, Kec. Semampir, Kota ...",603,+62 811-3008-894,4.7,saya kedua kalinya servis motor baru ke tempat...
1,Universal Bike HQ,"Jl. Raya Kalirungkut No.147, Kali Rungkut, Kec...",458,+62 31 99044187,4.8,saya kedua kalinya servis motor baru ke tempat...
2,Sun Rise Motor Tidar,"Jl. Tidar No.292, Tembok Dukuh, Kec. Bubutan, ...",296,+62 31 5341332,4.4,Pemilik toko suami istri melayani pelanggan dg...
3,Bengkel Cat Mobil Surabaya SIP - Speed Indo Pr...,"Jl. Tenggilis Tengah I No.28, Kendangsari, Kec...",260,+62 31 8496648,4.3,Pelayanan sangat luamaaaaaa sekali.....!!\nTid...
4,Untung Jaya Motor,"Banyu Urip Wetan V No.93, Putat Jaya, Kec. Saw...",255,+62 31 5677625,4.0,"Harga sparepartnya mahal, sekali aja servis di..."
5,Denco Motor,"No, Jl. Kapas Krampung No.236, Kota SBY, Jawa ...",246,-,4.5,Sangat kecewa dengan pelayanannya.\n\nPelayana...
6,Dasyi Jaya Motor,"Jl. Raya Pandugo No.44, Penjaringan Sari, Kec....",232,+62 31 8793323,4.3,Untuk orang yg g paham motor jgn servis disini...
7,Bengkel Proff Motor,"Jl.Petemon II No.100, Petemon, Kec. Sawahan, K...",206,+62 822-5767-2683,4.8,Servisnya mantap dan pelayanan cepat. Dan bara...
8,Seruling Motor & Knalpot NRP,"Dukuh Kupang Timur XX No.16, Pakis, Kec. Sawah...",138,+62 812-1718-7959,4.8,Mantapppp aslii. Pengerjaanya bagus sungguh se...

### STATISTIKA DESKRIPTIF

In [6]:
df1.describe()

           Review    Rating
count    9.000000  9.000000
mean   299.333333  4.511111
std    142.754159  0.284800
min    138.000000  4.000000
25%    232.000000  4.300000
50%    255.000000  4.500000
75%    296.000000  4.800000
max    603.000000  4.800000

## WEB 2

In [7]:
from bs4 import BeautifulSoup 
import requests 
import pandas as pd

In [8]:
url = "https://jejakpiknik.com/bengkel-motor-surabaya/"
req = requests.get(url)
print(req)

<Response [200]>

In [9]:
soup = BeautifulSoup(req.text, "html.parser")  
print(soup.link)

<link href="https://jejakpiknik.com/bengkel-motor-surabaya/" rel="canonical"/>

In [10]:
nama = []
alamat = []
nomer = []
komentar = []

nemu = soup.find('div', class_ = 'entry-content')

for i in nemu.find_all('h3'):
    nyaringnama = i.text
    nyaringalamat = i.find_next('p').text.split('\n')[0][8:]
    nyaringnomer = i.find_next('p').text.split('\n')
    
    if len(nyaringnomer) == 4:
        nyaringnomer = nyaringnomer[3]
    else:
        nyaringnomer = '-'
        
    
    nyaringkomentar = i.find_next('p').find_next('p').text
    
    nama.append(nyaringnama)
    alamat.append(nyaringalamat)
    nomer.append(nyaringnomer)
    komentar.append(nyaringkomentar)

In [11]:
df2 = pd.DataFrame({'Nama': nama, 'Alamat' : alamat, 'Nomer' : nomer, 'Komentar' : komentar })
df2

,Nama,Alamat,Nomer,Komentar
0,1. RX-King Godeng❤️,"Jl. Raya Wisma Lidah Kulon No.67, Lidah Kulon,...",No Telp: 0852-3115-1648,Tempat ini merupakan bengkel spesialis motor R...
1,2. Bengkel Bagong Press Velg❤️,"Jl. Raya Rungkut Menanggal No.6, Rungkut Menan...",No Telp: 0899-3349-683,"Sesuai dengan namanya, bengkel ini adalah temp..."
2,3. Ahass 13124 Daya❤️,"Jl. Menur Pumpungan No.72, Menur Pumpungan, Ke...",No Telp: 0857-3222-8185,"Nah, kalo tempat ini adalah bengkel resmi untu..."
3,4. Bratang Motor❤️,"Jl. Bratang Gede No.81, Ngagelrejo, Kecamatan ...",No Telp: (031) 5043715,Tempat ini menjual peralatan sepeda motor dan ...
4,5. IWS Motor Sport❤️,"Jl. Dukuh Kupang Timur XIV No.2, Pakis, Kecama...",No Telp: 0813-5721-8786,IWS adalah salah satu tempat yang tepat untuk ...
5,6. Bengkel Cat❤️,"Jl. Karang Rejo X No.3, Wonokromo, Kecamatan W...",No Telp: 0851-0066-9842,"Sesuai dengan namanya, tempat ini sangat cocok..."
6,7. Yamaha 99 Motor❤️,"Jl. Kedung Mangu Timur No.121, Sidotopo Wetan,...",No Telp: (031) 3732617,"Nah, kalo yang ini adalah salah satu bengkel r..."
7,8. Saudara Motor❤️,"Jl. Raya Mulyosari No.46, Kalisari, Kecamatan ...",-,Buat kalian yang mau servis di daerah Surabaya...
8,9. ACC Motor❤️,"Jl. Bumi Indah No.54, Lontar, Kecamatan Sambik...",No Telp: (031) 7406279,"Terletak tidak jauh dari Jalan Manukan, tempat..."
9,10. Platina Motor❤️,"Jl. Kertajaya No.16, Kertajaya, Kecamatan Gube...",No Telp: (031) 5020141,"Meskipun tokonya tidak terlalu besar, sparepar..."
10,11. Jok Sadel Motor Gesang❤️,"Jl. Raya Pagesangan No.63, Pagesangan, Kecamat...",-,Ingin servis jok motor? Cobalah untuk ke tempa...
11,12. 3H Motor❤️,"Jl. Barata Jaya No.11-11B, Baratajaya, Kecamat...",No Telp: 0858-5181-8800,3H Motorsport adalah tempat modifikasi yang ti...
12,13. Khimcil Garage❤️,"Jl. Pumpungan III, Menur Pumpungan, Kecamatan ...",-,Tempat ini merupakan bengkel spesialis restora...
13,14. Motorcycle RMS❤️,"Jl. Siwalankerto Jaya VI No.12, Siwalankerto, ...",No Telp: 0822-3432-5566,"Ada lagi nih, bengkel yang recommended buat se..."

In [12]:
df2.describe()

,Nama,Alamat,Nomer,Komentar
count,14,14,14,14
unique,14,14,12,14
top,1. RX-King Godeng❤️,"Jl. Raya Wisma Lidah Kulon No.67, Lidah Kulon,...",-,Tempat ini merupakan bengkel spesialis motor R...
freq,1,1,3,1